# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import random
from lib.f1_types import PacketLapData, F1PacketType
from .tests_parser_base import F1TypesTest

class TestPacketLapData(F1TypesTest):
    """
    Tests for TestPacketLapData
    """
    def setUp(self) -> None:
        """
        Set up the test
        """
        self.m_num_players = random.randint(1, 22)

    def test_f1_23_actual(self):
        """
        Test for F1 2023 with an actual game packet
        """

        random_header = F1TypesTest.getRandomHeader(F1PacketType.LAP_DATA, 23, self.m_num_players)
        raw_packet = (
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfaQ\x04C\xfaQ\x04C\x00\x00\x00"
            b"\x80\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'8\xf8B'8\xf8B\x00\x00\x00\x80\x02\x01\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x02\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\\q\xe8B\\q\xe8B\x00\x00\x00\x80\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x03\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00 l\xd8B l\xd8B\x00\x00\x00\x80\x04\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x04\x02\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Pm\xc8BPm\xc8B\x00"
            b"\x00\x00\x80\x05\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00rR\xa8BrR\xa8B\x00\x00\x00\x80\x07\x01\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x07\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbeD\x98B\xbeD\x98B\x00\x00\x00\x80\x08\x01\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x08\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\xdaf\x88B\xdaf\x88B\x00\x00\x00\x80\t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\t\x04\x02"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbd"
            b"\xacpB\xbd\xacpB\x00\x00\x00\x80\n\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\n\x04\x02\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa7\xd3PB\xa7\xd3PB\x00\x00"
            b"\x00\x80\x0b\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\xcd0BZ\xcd0B\x00\x00\x00\x80\x0c\x01\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x0c\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00C\xf0\x10BC\xf0\x10B\x00\x00\x00\x80\r\x01\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\r\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\xca\x12\xe2A\xca\x12\xe2A\x00\x00\x00\x80\x0e\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0e"
            b"\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x12m\xa1A\x12m\xa1A\x00\x00\x00\x80\x0f\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0f\x04\x02\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x92\xd5CA\x92\xd5CA"
            b"\x00\x00\x00\x80\x10\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x87Y\x86@\x87Y\x86@\x00\x00\x00\x80\x11"
            b"\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x11\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9a:\xb8B\x9a:\xb8B\x00\x00\x00\x80\x06\x01\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x06\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x08t\xc0\x00\x08t\xc0\x00\x00\x00\x80\x12\x01\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x12\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00@<\xc1\x00@<\xc1\x00\x00\x00\x80\x13\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x13\x04\x02"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd4"
            b"\x9e\xc1\x00\xd4\x9e\xc1\x00\x00\x00\x80\x14\x01\x00\x00\x02\x00\x00\x00\x00\x00\x00\x14\x04\x02\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            b"\x00\xff\xff"
        )
        expected_json = {
            "lap-data": [
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 132.32022094726562,
                    "total-distance": 132.32022094726562,
                    "safety-car-delta": -0.0,
                    "car-position": 1,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 1,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 124.10967254638672,
                    "total-distance": 124.10967254638672,
                    "safety-car-delta": -0.0,
                    "car-position": 2,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 2,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 116.22140502929688,
                    "total-distance": 116.22140502929688,
                    "safety-car-delta": -0.0,
                    "car-position": 3,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 3,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 108.211181640625,
                    "total-distance": 108.211181640625,
                    "safety-car-delta": -0.0,
                    "car-position": 4,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 4,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 100.2135009765625,
                    "total-distance": 100.2135009765625,
                    "safety-car-delta": -0.0,
                    "car-position": 5,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 5,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 84.16102600097656,
                    "total-distance": 84.16102600097656,
                    "safety-car-delta": -0.0,
                    "car-position": 7,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 7,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 76.13426208496094,
                    "total-distance": 76.13426208496094,
                    "safety-car-delta": -0.0,
                    "car-position": 8,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 8,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 68.20088195800781,
                    "total-distance": 68.20088195800781,
                    "safety-car-delta": -0.0,
                    "car-position": 9,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 9,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 60.1686897277832,
                    "total-distance": 60.1686897277832,
                    "safety-car-delta": -0.0,
                    "car-position": 10,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 10,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 52.20669174194336,
                    "total-distance": 52.20669174194336,
                    "safety-car-delta": -0.0,
                    "car-position": 11,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 11,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 44.200538635253906,
                    "total-distance": 44.200538635253906,
                    "safety-car-delta": -0.0,
                    "car-position": 12,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 12,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 36.2346305847168,
                    "total-distance": 36.2346305847168,
                    "safety-car-delta": -0.0,
                    "car-position": 13,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 13,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 28.259174346923828,
                    "total-distance": 28.259174346923828,
                    "safety-car-delta": -0.0,
                    "car-position": 14,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 14,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 20.17825698852539,
                    "total-distance": 20.17825698852539,
                    "safety-car-delta": -0.0,
                    "car-position": 15,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 15,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 12.239641189575195,
                    "total-distance": 12.239641189575195,
                    "safety-car-delta": -0.0,
                    "car-position": 16,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 16,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 4.198428630828857,
                    "total-distance": 4.198428630828857,
                    "safety-car-delta": -0.0,
                    "car-position": 17,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 17,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 92.11445617675781,
                    "total-distance": 92.11445617675781,
                    "safety-car-delta": -0.0,
                    "car-position": 6,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 6,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": -3.81298828125,
                    "total-distance": -3.81298828125,
                    "safety-car-delta": -0.0,
                    "car-position": 18,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 18,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": -11.765625,
                    "total-distance": -11.765625,
                    "safety-car-delta": -0.0,
                    "car-position": 19,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 19,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": -19.853515625,
                    "total-distance": -19.853515625,
                    "safety-car-delta": -0.0,
                    "car-position": 20,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "2",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 20,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0,
                    "speed-trap-fastest-lap": 0
                }
            ],
            "lap-data-count": 22,
            "time-trial-pb-car-idx": -1,
            "time-trial-rival-car-idx": -1
        }

        parsed_packet = PacketLapData(random_header, raw_packet)
        parsed_json = parsed_packet.toJSON()
        self.jsonComparisionUtil(expected_json, parsed_json)

    def test_f1_24_actual(self):
        """
        Test for F1 2024 with an actual game packet
        """

        random_header = F1TypesTest.getRandomHeader(F1PacketType.LAP_DATA, 24, self.m_num_players)
        raw_packet = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x90\xd4yB\x90\xd4yB\x00\x00\x00\x80\x08\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc8\x1f\xedB\xc8\x1f\xedB\x00\x00\x00\x80\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1e\xee\xacB\x1e\xee\xacB\x00\x00\x00\x80\x05\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x006\xf7\x8cB6\xf7\x8cB\x00\x00\x00\x80\x07\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\n\xd9YB\n\xd9YB\x00\x00\x00\x80\t\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\t\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00y\x1d\xbdBy\x1d\xbdB\x00\x00\x00\x80\x04\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x1a\xddB\x80\x1a\xddB\x00\x00\x00\x80\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xab\t\xcdB\xab\t\xcdB\x00\x00\x00\x80\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xcc9B\xfe\xcc9B\x00\x00\x00\x80\n\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\n\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa7\xf5\x9cB\xa7\xf5\x9cB\x00\x00\x00\x80\x06\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x04\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff'
        expected_json = {
            "lap-data": [
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 62.45758056640625,
                    "total-distance": 62.45758056640625,
                    "safety-car-delta": -0.0,
                    "car-position": 8,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 8,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 118.56207275390625,
                    "total-distance": 118.56207275390625,
                    "safety-car-delta": -0.0,
                    "car-position": 1,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 1,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 86.46507263183594,
                    "total-distance": 86.46507263183594,
                    "safety-car-delta": -0.0,
                    "car-position": 5,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 5,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 70.48283386230469,
                    "total-distance": 70.48283386230469,
                    "safety-car-delta": -0.0,
                    "car-position": 7,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 7,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 54.461952209472656,
                    "total-distance": 54.461952209472656,
                    "safety-car-delta": -0.0,
                    "car-position": 9,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 9,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 94.55756378173828,
                    "total-distance": 94.55756378173828,
                    "safety-car-delta": -0.0,
                    "car-position": 4,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 4,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 110.5517578125,
                    "total-distance": 110.5517578125,
                    "safety-car-delta": -0.0,
                    "car-position": 2,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 2,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 102.51888275146484,
                    "total-distance": 102.51888275146484,
                    "safety-car-delta": -0.0,
                    "car-position": 3,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 3,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 46.45018768310547,
                    "total-distance": 46.45018768310547,
                    "safety-car-delta": -0.0,
                    "car-position": 10,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 10,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 78.47978973388672,
                    "total-distance": 78.47978973388672,
                    "safety-car-delta": -0.0,
                    "car-position": 6,
                    "current-lap-num": 1,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 6,
                    "driver-status": "ON_TRACK",
                    "result-status": "ACTIVE",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 255
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                },
                {
                    "last-lap-time-in-ms": 0,
                    "last-lap-time-str": "00:00.000",
                    "current-lap-time-in-ms": 0,
                    "current-lap-time-str": "00:00.000",
                    "sector-1-time-in-ms": 0,
                    "sector-1-time-minutes": 0,
                    "sector-1-time-str": "0.000",
                    "sector-2-time-in-ms": 0,
                    "sector-2-time-minutes": 0,
                    "sector-2-time-str": "0.000",
                    "delta-to-car-in-front-in-ms": 0,
                    "delta-to-race-leader-in-ms": 0,
                    "lap-distance": 0.0,
                    "total-distance": 0.0,
                    "safety-car-delta": 0.0,
                    "car-position": 0,
                    "current-lap-num": 0,
                    "pit-status": "NONE",
                    "num-pit-stops": 0,
                    "sector": "0",
                    "current-lap-invalid": False,
                    "penalties": 0,
                    "total-warnings": 0,
                    "corner-cutting-warnings": 0,
                    "num-unserved-drive-through-pens": 0,
                    "num-unserved-stop-go-pens": 0,
                    "grid-position": 0,
                    "driver-status": "IN_GARAGE",
                    "result-status": "INVALID",
                    "pit-lane-timer-active": False,
                    "pit-lane-time-in-lane-in-ms": 0,
                    "pit-stop-timer-in-ms": 0,
                    "pit-stop-should-serve-pen": 0,
                    "speed-trap-fastest-speed": 0.0,
                    "speed-trap-fastest-lap": 0
                }
            ],
            "lap-data-count": 22,
            "time-trial-pb-car-idx": -1,
            "time-trial-rival-car-idx": -1
        }

        parsed_packet = PacketLapData(random_header, raw_packet)
        parsed_json = parsed_packet.toJSON()
        self.jsonComparisionUtil(expected_json, parsed_json)