# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import random
from lib.f1_types import CarSetupData, PacketCarSetupData, F1PacketType, PacketHeader
from .tests_parser_base import F1TypesTest

class TestPacketCarSetupData(F1TypesTest):
    """
    Tests for TestPacketCarSetupData
    """
    def setUp(self) -> None:
        """
        Set up the test
        """
        self.m_num_players = 22
        self.m_header_23 = F1TypesTest.getRandomHeader(F1PacketType.CAR_SETUPS, 23, self.m_num_players)
        self.m_header_24 = F1TypesTest.getRandomHeader(F1PacketType.CAR_SETUPS, 24, self.m_num_players)

    def test_f1_24_random(self):
        """
        Test for F1 2024 with an randomly generated packet
        """

        random_car_setups = [self._getRandomCarSetupData(self.m_header_24) for _ in range(self.m_num_players)]

        generated_test_obj = PacketCarSetupData.from_values(
            self.m_header_24, random_car_setups, next_front_wing_value=F1TypesTest.getRandomFloat())
        serialised_test_obj = generated_test_obj.to_bytes()
        header_bytes = serialised_test_obj[:PacketHeader.PACKET_LEN]
        parsed_header = PacketHeader(header_bytes)
        self.assertEqual(self.m_header_24, parsed_header)
        payload_bytes = serialised_test_obj[PacketHeader.PACKET_LEN:]
        parsed_obj = PacketCarSetupData(parsed_header, payload_bytes)
        self.assertEqual(generated_test_obj, parsed_obj)
        self.assertEqual(generated_test_obj.toJSON(), parsed_obj.toJSON())

    def test_f1_23_random(self):
        """
        Test for F1 2023 with an randomly generated packet
        """

        random_car_setups = [self._getRandomCarSetupData(self.m_header_23) for _ in range(self.m_num_players)]

        generated_test_obj = PacketCarSetupData.from_values(self.m_header_23, random_car_setups)
        serialised_test_obj = generated_test_obj.to_bytes()
        header_bytes = serialised_test_obj[:PacketHeader.PACKET_LEN]
        parsed_header = PacketHeader(header_bytes)
        self.assertEqual(self.m_header_23, parsed_header)
        payload_bytes = serialised_test_obj[PacketHeader.PACKET_LEN:]
        parsed_obj = PacketCarSetupData(parsed_header, payload_bytes)
        self.assertEqual(generated_test_obj, parsed_obj)
        self.assertEqual(generated_test_obj.toJSON(), parsed_obj.toJSON())

    def test_f1_24_actual(self):
        """
        Test for F1 2024 with an actual packet
        """

        raw_packet = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x0b\x19F\x00\x00`\xc043\xf3\xbf\xcd\xccL=ff\xe6>%\x0c\x15\t\x16Bd:\x1e\xcd\xcc\xa8A\xcd\xcc\xa8A33\xc7A33\xc7A\x06\x00\x00 A\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@A'
        expected_json = {
            "car-setups": [
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 12,
                    "rear-wing": 11,
                    "on-throttle": 25,
                    "off-throttle": 70,
                    "front-camber": -3.5,
                    "rear-camber": -1.9000000953674316,
                    "front-toe": 0.05000000074505806,
                    "rear-toe": 0.44999998807907104,
                    "front-suspension": 37,
                    "rear-suspension": 12,
                    "front-anti-roll-bar": 21,
                    "rear-anti-roll-bar": 9,
                    "front-suspension-height": 22,
                    "rear-suspension-height": 66,
                    "brake-pressure": 100,
                    "brake-bias": 58,
                    "engine-braking": 30,
                    "rear-left-tyre-pressure": 21.100000381469727,
                    "rear-right-tyre-pressure": 21.100000381469727,
                    "front-left-tyre-pressure": 24.899999618530273,
                    "front-right-tyre-pressure": 24.899999618530273,
                    "ballast": 6,
                    "fuel-load": 10.0,
                    "is-valid": True
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                }
            ]
        }

        parsed_packet = PacketCarSetupData(self.m_header_24, raw_packet)
        parsed_json = parsed_packet.toJSON()
        self.assertEqual(expected_json, parsed_json)

    def test_f1_23_actual(self):
        """
        Test for F1 2023 with an actual game packet
        """

        raw_packet = b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19\x12<5\x00\x00 \xc0\x00\x00\x80\xbf\x00\x00\x00\x00\xcd\xcc\xcc='\x05\x07\x01!(d8\x00\x00\xa4A\x00\x00\xa4Aff\xb6Aff\xb6A\x06\x00\x00\xa0A\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        expected_json = {
            "car-setups": [
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 25,
                    "rear-wing": 18,
                    "on-throttle": 60,
                    "off-throttle": 53,
                    "front-camber": -2.5,
                    "rear-camber": -1.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.10000000149011612,
                    "front-suspension": 39,
                    "rear-suspension": 5,
                    "front-anti-roll-bar": 7,
                    "rear-anti-roll-bar": 1,
                    "front-suspension-height": 33,
                    "rear-suspension-height": 40,
                    "brake-pressure": 100,
                    "brake-bias": 56,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 20.5,
                    "rear-right-tyre-pressure": 20.5,
                    "front-left-tyre-pressure": 22.799999237060547,
                    "front-right-tyre-pressure": 22.799999237060547,
                    "ballast": 6,
                    "fuel-load": 20.0,
                    "is-valid": True
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                },
                {
                    "front-wing": 0,
                    "rear-wing": 0,
                    "on-throttle": 0,
                    "off-throttle": 0,
                    "front-camber": 0.0,
                    "rear-camber": 0.0,
                    "front-toe": 0.0,
                    "rear-toe": 0.0,
                    "front-suspension": 0,
                    "rear-suspension": 0,
                    "front-anti-roll-bar": 0,
                    "rear-anti-roll-bar": 0,
                    "front-suspension-height": 0,
                    "rear-suspension-height": 0,
                    "brake-pressure": 0,
                    "brake-bias": 0,
                    "engine-braking": 0,
                    "rear-left-tyre-pressure": 0.0,
                    "rear-right-tyre-pressure": 0.0,
                    "front-left-tyre-pressure": 0.0,
                    "front-right-tyre-pressure": 0.0,
                    "ballast": 0,
                    "fuel-load": 0.0,
                    "is-valid": False
                }
            ]
        }

        parsed_packet = PacketCarSetupData(self.m_header_23, raw_packet)
        parsed_json = parsed_packet.toJSON()
        self.assertEqual(expected_json, parsed_json)

    def _getRandomCarSetupData(self, header: PacketHeader) -> CarSetupData:
        """
        Generates a random car setup data object

        Args:
            header (PacketHeader): The header of the packet

        Returns:
            CarSetupData: The random car setup data object
        """

        if header.m_gameYear == 23:
            engine_braking = 0
        else:
            engine_braking = random.getrandbits(8)
        return CarSetupData.from_values(
            header.m_gameYear,
            front_wing=random.getrandbits(8),
            rear_wing=random.getrandbits(8),
            on_throttle=random.getrandbits(8),
            off_throttle=random.getrandbits(8),
            front_camber=F1TypesTest.getRandomFloat(),
            rear_camber=F1TypesTest.getRandomFloat(),
            front_toe=F1TypesTest.getRandomFloat(),
            rear_toe=F1TypesTest.getRandomFloat(),
            front_suspension=random.getrandbits(8),
            rear_suspension=random.getrandbits(8),
            front_anti_roll_bar=random.getrandbits(8),
            rear_anti_roll_bar=random.getrandbits(8),
            front_suspension_height=random.getrandbits(8),
            rear_suspension_height=random.getrandbits(8),
            brake_pressure=random.getrandbits(8),
            brake_bias=random.getrandbits(8),
            rear_left_tyre_pressure=F1TypesTest.getRandomFloat(),
            rear_right_tyre_pressure=F1TypesTest.getRandomFloat(),
            front_left_tyre_pressure=F1TypesTest.getRandomFloat(),
            front_right_tyre_pressure=F1TypesTest.getRandomFloat(),
            ballast=random.getrandbits(8),
            fuel_load=F1TypesTest.getRandomFloat(),
            engine_braking=engine_braking
        )
