# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -------------------------------------- IMPORTS -----------------------------------------------------------------------

import asyncio
import json
import logging
from dataclasses import dataclass
from typing import Any, Awaitable, Callable, Dict, List, Literal, Optional

from fastmcp import FastMCP
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool

from meta.meta import APP_NAME

from .tools.get_race_table import get_race_table, RACE_TABLE_OUTPUT_SCHEMA
from .tools.get_session_info import get_session_info, SESSION_INFO_OUTPUT_SCHEMA
from .tools.get_driver_lap_times import get_driver_lap_times, DRIVER_LAP_TIMES_OUTPUT_SCHEMA
from .tools.get_session_events_for_driver import get_session_events_for_driver, DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA

TransportType = Literal["http", "stdio"]

# -------------------------------------- FUNCTIONS ---------------------------------------------------------------------

class MCPBridge:
    """FastMCP-based MCP Bridge for sim racing telemetry"""

    WELCOME_MSG = """\
This MCP server provides authoritative, local, live telemetry and session state
for a sim racing session generated by the Pits n' Giggles application.

Rules:
- Live session data is ONLY available through MCP tools.
- Do NOT use web search for session-specific information.
- Treat MCP tool responses as the single source of truth.
- If a tool reports available=false, the data is currently unavailable.
- If a tool reports connected=false, the data source is disconnected. The data may be outdated.
    - Check for the last-update-timestamp field if available and use it to determine data freshness.
- Do not speculate or infer missing information.

Tools exposed by this MCP provide structured snapshots of the current session.
They are safe to call whenever up-to-date information is required.

TIME AND UNIT HANDLING (MANDATORY):

All time values returned by MCP tools are in milliseconds unless explicitly stated otherwise.

You MUST convert all time values before presenting them to the user using the following formats:

- Lap times MUST be formatted as: mm:ss.sss
- Sector times MUST be formatted as: ss.sss
- Time deltas MUST be formatted as: +s.sss or -s.sss

Rules:
- NEVER display raw milliseconds to the user.
- NEVER mix formats.
- If a value cannot be converted due to missing context, state that it is unavailable.

"""

    def __init__(
        self,
        core_server_port: int,
        logger: logging.Logger,
        version: str,
        *,
        transport: TransportType = "stdio",
        host: str = "127.0.0.1",
        port: int = 8000,
    ) -> None:
        self.logger = logger
        self.version = version
        self.transport = transport
        self.host = host
        self.port = port
        self.core_server_port = core_server_port


        # FastMCP server
        self.mcp = FastMCP(
            name=f"{APP_NAME} MCP Server",
            instructions=self.WELCOME_MSG,
            strict_input_validation=True,
            version=self.version,
        )

        self._register_tools()

        self.logger.debug("MCPBridge initialized (transport=%s)", transport)

    # ------------------------------------------------------------------
    # Tool registration (unchanged semantics)
    # ------------------------------------------------------------------

    def _register_tools(self) -> None:

        @self.mcp.tool(
            name="get_session_info",
            description="Get current session information",
            title="Session Information - Globals",
            tags={"session", "weather", "safetyCar"},
            output_schema=SESSION_INFO_OUTPUT_SCHEMA,
        )
        async def get_session_info_tool():
            rsp = get_session_info(self.logger)
            self.logger.debug(
                "get_session_info called: available=%s",
                rsp.get("available", False),
            )
            return rsp

        @self.mcp.tool(
            name="get_race_table",
            description="Full Race Snapshot",
            title="Current Race State",
            tags={
                "race",
                "standings",
                "compare",
                "snapshot",
            },
            output_schema=RACE_TABLE_OUTPUT_SCHEMA,
        )
        async def get_race_table_tool():
            rsp = get_race_table(self.logger)
            self.logger.debug(
                "get_race_table called: available=%s",
                rsp.get("available", False),
            )
            return rsp

        @self.mcp.tool(
            name="get_driver_lap_times",
            description="Get lap time history for the driver with the given index (0-21)",
            title="Driver Lap Times (History)",
            tags={
                "driver",
                "laps",
                "timing",
                "history",
                "consistency",
                "pace",
            },
            output_schema=DRIVER_LAP_TIMES_OUTPUT_SCHEMA,
        )
        async def handle_get_driver_lap_times(driver_index: int) -> Dict[str, Any]:
            self.logger.debug("get_driver_lap_times called: driver_index=%s", driver_index)
            return await get_driver_lap_times(
                core_server_port=self.core_server_port,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self.mcp.tool(
            name="get_session_events_for_driver",
            description="Get race control messages for events in the current session for the driver with the given index (0-21)",
            title="Driver Race Control Messages (History)",
            tags={
                "driver",
                "events",
                "key",
                "notable",
                "raceControl",
                "incidents",
            },
            output_schema=DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA,
        )
        async def handle_get_session_events_for_driver(driver_index: int) -> Dict[str, Any]:
            self.logger.debug("get_session_events_for_driver called: driver_index=%s", driver_index)
            return await get_session_events_for_driver(
                core_server_port=self.core_server_port,
                logger=self.logger,
                driver_index=driver_index,
            )

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def run(self) -> None:
        """
        Long-running MCP server coroutine.
        Intended to be scheduled with asyncio.create_task().
        """

        logging.getLogger("uvicorn.error").setLevel(logging.CRITICAL)
        logging.getLogger("uvicorn.lifespan").setLevel(logging.CRITICAL)
        logging.getLogger("starlette").setLevel(logging.CRITICAL)

        try:
            if self.transport == "http":
                self.logger.info(
                    "Starting MCP server (transport=%s port=%s)", self.transport, self.port
                )
                await self.mcp.run_async(
                    transport="http",
                    host=self.host,
                    port=self.port,
                    show_banner=False,
                )
            elif self.transport == "stdio":
                self.logger.info(
                    "Starting MCP server (transport=%s)", self.transport
                )
                await self.mcp.run_async(
                    transport="stdio",
                    show_banner=False,
                )
            else:
                raise ValueError(f"Unsupported transport: {self.transport}")

        except asyncio.CancelledError:
            return # silent handling - this is expected

        except Exception as e: # pylint: disable=broad-except
            self.logger.exception("MCP server failed: %s", e)
