# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -------------------------------------- IMPORTS -----------------------------------------------------------------------

import logging
import json
from typing import Dict, Any, List, Callable, Awaitable, Optional
from dataclasses import dataclass

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool

from .tools_infra import ToolRegistry
from meta.meta import APP_NAME

from .tools.get_session_info import get_session_info
from .tools.get_race_table import get_race_table

# -------------------------------------- FUNCTIONS ---------------------------------------------------------------------

class MCPBridge:
    """MCP Bridge for sim racing telemetry"""

    WELCOME_MSG = """\
This MCP server provides authoritative, local, live telemetry and session state
for a sim racing session generated by the Pits n' Giggles application.

Rules:
- Live session data is ONLY available through MCP tools.
- Do NOT use web search for session-specific information.
- Treat MCP tool responses as the single source of truth.
- If a tool reports available=false, the data is currently unavailable.
- If a tool reports connected=false, the data source is disconnected. The data may be outdated.
    - Check for the last-update-timestamp field if available and use it to determine data freshness.
- Do not speculate or infer missing information.

Tools exposed by this MCP provide structured snapshots of the current session.
They are safe to call whenever up-to-date information is required.

TIME AND UNIT HANDLING (MANDATORY):

All time values returned by MCP tools are in milliseconds unless explicitly stated otherwise.

You MUST convert all time values before presenting them to the user using the following formats:

- Lap times MUST be formatted as: mm:ss.sss
- Sector times MUST be formatted as: ss.sss
- Time deltas MUST be formatted as: +s.sss or -s.sss

Rules:
- NEVER display raw milliseconds to the user.
- NEVER mix formats.
- If a value cannot be converted due to missing context, state that it is unavailable.

"""

    def __init__(self, logger: logging.Logger, version: str) -> None:
        self.registry: ToolRegistry = ToolRegistry()
        self.logger: logging.Logger = logger
        self.version: str = version
        self._register_tools()
        self.logger.debug("MCPBridge initialized with tools: %s", list(self.registry._tools.keys()))

    def _register_tools(self):
        """Register all tools"""

        @self.registry.tool(
            name="get_session_info",
            description="Get current session information",
        )
        async def handle_get_session_info(
            context: "MCPBridge",
            arguments: Dict[str, Any],
        ) -> Dict[str, Any]:
            rsp = get_session_info(self.logger)
            self.logger.debug("handle_get_session_info called with arguments: %s. rsp: available=%s",
                              arguments, rsp.get("available", False))
            return rsp

        @self.registry.tool(
            name="get_race_table",
            description="Get current race table",
        )
        async def handle_get_race_table(
            context: "MCPBridge",
            arguments: Dict[str, Any],
        ) -> Dict[str, Any]:
            rsp = get_race_table(self.logger)
            self.logger.debug("handle_get_race_table called with arguments: %s. rsp: available=%s",
                              arguments, rsp.get("available", False))
            return rsp

    def _init_infra(self, server: Server) -> None:
        """Initialize infrastructure components if any"""
        @server.list_tools()
        async def list_tools():
            tools = self.registry.get_tool_list()
            self.logger.debug("Listing registered tools: %s", tools)
            return tools

        @server.call_tool()
        async def call_tool(name: str, arguments: Dict[str, Any]):
            try:
                return await self.registry.call_tool(name, arguments, self)
            except Exception as e:
                return [{
                    "type": "text",
                    "text": f"Error: {str(e)}"
                }]

    # ========================================================================
    # MCP Server Setup
    # ========================================================================

    async def run(self):
        """Main entry point - run MCP server over stdio"""
        server = Server(
            name=f"{APP_NAME} MCP Server",
            version=self.version,
            instructions=self.WELCOME_MSG,)
        self._init_infra(server)
        self.logger.debug("MCP Server initialized.")

        # Run MCP server
        async with stdio_server() as (read_stream, write_stream):
            await server.run(
                read_stream,
                write_stream,
                server.create_initialization_options()
            )
