# MIT License
#
# Copyright (c) [2024] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# -------------------------------------- IMPORTS -----------------------------------------------------------------------

import asyncio
import logging
import socket
from typing import Any, Dict, Literal

import uvicorn
from fastmcp import FastMCP
from mcp.types import ToolAnnotations
from starlette.requests import Request
from starlette.responses import JSONResponse

from lib.error_status import PngError, PngHttpPortInUseError
from lib.web_server import get_socket_for_uvicorn
from meta.meta import APP_NAME

from .tools.get_driver_lap_times import (DRIVER_LAP_TIMES_OUTPUT_SCHEMA,
                                         get_driver_lap_times)
from .tools.get_drivers_list import (DRIVERS_LIST_OUTPUT_SCHEMA,
                                     get_drivers_list)
from .tools.get_player_driver_info import (PLAYER_DRIVER_INFO_OUTPUT_SCHEMA,
                                           get_player_driver_info)
from .tools.get_race_table import RACE_TABLE_OUTPUT_SCHEMA, get_race_table
from .tools.get_session_events_for_driver import (
    DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA, get_session_events_for_driver)
from .tools.get_session_info import (SESSION_INFO_OUTPUT_SCHEMA,
                                     get_session_info)

TransportType = Literal["http", "stdio"]

# -------------------------------------- FUNCTIONS ---------------------------------------------------------------------

class MCPBridge:
    """FastMCP-based MCP Bridge for sim racing telemetry"""

    WELCOME_MSG = """\
This MCP server provides authoritative, local, live telemetry and session state
for a sim racing session generated by the Pits n' Giggles application.

Rules:
- Live session data is ONLY available through MCP tools.
- Do NOT use web search for session-specific information.
- Treat MCP tool responses as the single source of truth.
- If a tool reports available=false, the data is currently unavailable.
- If a tool reports connected=false, the data source is disconnected. The data may be outdated.
    - Check for the last-update-timestamp field if available and use it to determine data freshness.
- Do not speculate or infer missing information.

Tools exposed by this MCP provide structured snapshots of the current session.
They are safe to call whenever up-to-date information is required.

TIME AND UNIT HANDLING (MANDATORY):

All time values returned by MCP tools are in milliseconds unless explicitly stated otherwise.

You MUST convert all time values before presenting them to the user using the following formats:

- Lap times MUST be formatted as: mm:ss.sss
- Sector times MUST be formatted as: ss.sss
- Time deltas MUST be formatted as: +s.sss or -s.sss

Rules:
- NEVER display raw milliseconds to the user.
- NEVER mix formats.
- If a value cannot be converted due to missing context, state that it is unavailable.

"""

    def __init__(
        self,
        core_server_port: int,
        logger: logging.Logger,
        version: str,
        *,
        transport: TransportType = "stdio",
        host: str = "127.0.0.1",
        port: int = 8000,
    ) -> None:
        self.logger = logger
        self.version = version
        self.transport = transport
        self.host = host
        self.port = port
        self.core_server_port = core_server_port


        # FastMCP server
        self.mcp = FastMCP(
            name=f"{APP_NAME} MCP Server",
            instructions=self.WELCOME_MSG,
            strict_input_validation=True,
            version=self.version,
        )

        self._register_tools()

        self.logger.debug("MCPBridge initialized (transport=%s)", transport)

    # ------------------------------------------------------------------
    # Tool registration (unchanged semantics)
    # ------------------------------------------------------------------

    def _register_tools(self) -> None:

        @self.mcp.tool(
            name="get_session_info",
            description="Get current session information",
            title="Session Information - Globals",
            tags={"session", "weather", "safetyCar"},
            output_schema=SESSION_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Session Information",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_session_info_tool():
            rsp = get_session_info(self.logger)
            self.logger.debug(
                "get_session_info called: available=%s",
                rsp.get("available", False),
            )
            return rsp

        @self.mcp.tool(
            name="get_race_table",
            description="Full Race Snapshot",
            title="Current Race State",
            tags={
                "race",
                "standings",
                "compare",
                "snapshot",
            },
            output_schema=RACE_TABLE_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Current Race State",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_race_table_tool():
            rsp = get_race_table(self.logger)
            self.logger.debug(
                "get_race_table called: available=%s",
                rsp.get("available", False),
            )
            return rsp

        @self.mcp.tool(
            name="get_drivers_list",
            description="Get drivers list",
            title="Drivers List",
            tags={
                "drivers",
                "session",
                "participants",
            },
            output_schema=DRIVERS_LIST_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Drivers List",
                readOnlyHint=True,
                openWorldHint=False,
            )
        )
        async def get_drivers_list_tool():
            rsp = get_drivers_list(self.logger)
            self.logger.debug(
                "get_drivers_list called: available=%s",
                rsp.get("available", False),
            )
            return rsp

        @self.mcp.tool(
            name="get_driver_lap_times",
            description="Get lap time history for the driver with the given index (0-21)",
            title="Driver Lap Times (History)",
            tags={
                "driver",
                "laps",
                "timing",
                "history",
                "consistency",
                "pace",
            },
            output_schema=DRIVER_LAP_TIMES_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Lap Times (History)",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_driver_lap_times(driver_index: int) -> Dict[str, Any]:
            self.logger.debug("get_driver_lap_times called: driver_index=%s", driver_index)
            return await get_driver_lap_times(
                core_server_port=self.core_server_port,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self.mcp.tool(
            name="get_session_events_for_driver",
            description="Get race control messages for events in the current session for the driver with the given index (0-21)",
            title="Driver Race Control Messages (History)",
            tags={
                "driver",
                "events",
                "key",
                "notable",
                "raceControl",
                "incidents",
            },
            output_schema=DRIVER_SESSION_EVENTS_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Driver Race Control Messages (History)",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_session_events_for_driver(driver_index: int) -> Dict[str, Any]:
            self.logger.debug("get_session_events_for_driver called: driver_index=%s", driver_index)
            return await get_session_events_for_driver(
                core_server_port=self.core_server_port,
                logger=self.logger,
                driver_index=driver_index,
            )

        @self.mcp.tool(
            name="get_player_driver_info",
            description="Get player driver info. Get index, name, team, etc for the player/reference driver",
            title="Player/Reference Driver Info",
            tags={
                "player",
                "reference",
                "ref",
                "pov",
                "driver",
                "info",
            },
            output_schema=PLAYER_DRIVER_INFO_OUTPUT_SCHEMA,
            annotations=ToolAnnotations(
                title="Player/Reference Driver Info",
                readOnlyHint=True,
                openWorldHint=False,
            ),
        )
        async def handle_get_player_driver_info():
            return get_player_driver_info(self.logger)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def run(self) -> None:
        """
        Long-running MCP server coroutine.
        Intended to be scheduled with asyncio.create_task().
        """

        logging.getLogger("uvicorn.error").setLevel(logging.CRITICAL)
        logging.getLogger("uvicorn.lifespan").setLevel(logging.CRITICAL)
        logging.getLogger("starlette").setLevel(logging.CRITICAL)

        try:
            if self.transport == "http":
                # 1. Bind the socket ourselves — this is where port-conflict
                #    errors surface cleanly, before uvicorn is involved at all.
                sock = self._bind_socket()
                self.logger.info("Starting MCP server (transport=%s port=%s)", self.transport, self.port)

                # 2. Get the ASGI app out of FastMCP without starting a server.
                asgi_app = self.mcp.http_app()
                asgi_app.add_route("/test", self._test_endpoint, methods=["GET"])

                # 3. Configure uvicorn but tell it NOT to bind — we already did.
                config = uvicorn.Config(
                    app=asgi_app,
                    host=self.host,
                    port=self.port,
                    log_level="critical",   # we use our own logger
                    access_log=False,
                )

                # Since we're running uvicorn ourselves, we need to lay hands on FastMCP's internals for cleanup
                server = uvicorn.Server(config)
                async with self.mcp._lifespan_manager():
                    await server.serve(sockets=[sock])

            elif self.transport == "stdio":
                self.logger.info(
                    "Starting MCP server (transport=%s)", self.transport
                )
                await self.mcp.run_async(
                    transport="stdio",
                    show_banner=False,
                )
            else:
                raise ValueError(f"Unsupported transport: {self.transport}")

        except asyncio.CancelledError:
            return # silent handling - this is expected

        # Handled in main
        except PngError:
            raise

        except Exception as e:
            self.logger.exception("MCP server failed: %s", e)
            raise

    def _bind_socket(self) -> socket.socket:
        """Create and bind a TCP socket, raising on port conflict.

        Platform-specific options:
        - Windows: SO_EXCLUSIVEADDRUSE makes bind() fail immediately when the
          port is already in use.  Without it Windows silently allows the bind.
        - Unix/Linux/macOS: SO_REUSEADDR lets us bind to a port that is in
          TIME_WAIT (safe for quick restart) but still fails when another
          process is actively listening.
        """
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock = get_socket_for_uvicorn(self.port)
            return sock
        except PngHttpPortInUseError as e:
            self.logger.exception("Port %d is already in use", self.port)
            raise e
        except OSError as e:
            self.logger.exception("Failed to start server: %s", e)
            raise

    async def _test_endpoint(self, _request: Request) -> str:
        """Simple test endpoint that returns text."""
        return JSONResponse({
            "message": f"Pits n' Giggles MCP Server v{self.version}",
        })
