# MIT License
#
# Copyright (c) [2025] [Ashwin Natarajan]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# ----------------------------------------------------------------------------------------------------------------------

"""Build-time renderer for the PyInstaller splash screen image.

PyInstaller's splash screen is a single static PNG plus one live text line: the Tcl script is
generated by ``PyInstaller/building/splash_templates.py`` and exposes no hook for custom widgets.
The PNG therefore *is* the splash UI. This module paints it with QPainter (PySide6 is already a
dependency, so no extra build-time packages are needed).

The image is generated at build time rather than committed so the version string can never go
stale. ``png.spec`` calls :func:`render_splash` while assembling the bundle.

Run standalone to preview the design without a full build::

    python scripts/gen_splash.py -o preview.png
"""

# -------------------------------------- IMPORTS -----------------------------------------------------------------------

import argparse
import os
import sys
from typing import Optional

# QPainter needs a QGuiApplication, but this runs headless inside the build. Must be set before
# PySide6 initialises its platform plugin.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

# Allow running this file directly (python scripts/gen_splash.py) as well as importing it from
# png.spec, which inserts scripts/ on sys.path rather than the project root.
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

# pylint: disable=wrong-import-position
from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QFont, QFontDatabase, QFontMetrics, QGuiApplication, QImage, QPainter, QPixmap

from lib.version import get_version
from meta.meta import APP_NAME

# -------------------------------------- CONSTANTS ---------------------------------------------------------------------

#: Final pixel dimensions. The Tk splash is not DPI-aware and scales nothing, so the image is
#: painted at exactly the size it will be displayed at; rendering at 2x would only blur it.
CANVAS_W = 480
CANVAS_H = 240

#: Windows implements splash transparency with a colour key of pure magenta
#: (``wm attributes . -transparentcolor magenta``, see PyInstaller's splash_templates.py).
#: Any '#ff00ff' pixel would be punched out of the window, so no colour here may equal it.
BG_COLOR = "#1e1e1e"
TITLE_COLOR = "#ffffff"
VERSION_COLOR = "#9a9a9a"

LOGO_SIZE = 112
LOGO_X = 32
LOGO_Y = 48

#: Left edge of the text column, to the right of the logo.
TEXT_X = 184
#: Text baselines. Chosen so the title/version block centres on the logo (y=104), while leaving
#: the bottom band clear for the loading line drawn at LOADING_POS.
TITLE_BASELINE_Y = 102
VERSION_BASELINE_Y = 130
#: Right margin the text column must not cross.
TEXT_RIGHT_MARGIN = 24

TITLE_PT_MAX = 24
TITLE_PT_MIN = 14
VERSION_PT_MAX = 12
VERSION_PT_MIN = 7

#: Static "loading" line in the bottom-left, mirroring the reference design. This is baked into
#: the image rather than drawn by PyInstaller: its live text field is driven by the bootloader
#: with per-file extraction progress, which is far more detail than is wanted here. png.spec
#: therefore builds the Splash target without any text options at all.
LOADING_TEXT = "Loading..."
LOADING_POS = (24, 216)
LOADING_PX = 13
LOADING_COLOR = "#b0b0b0"

LOGO_PATH = os.path.join(_PROJECT_ROOT, "assets", "logo.png")
TITLE_FONT_PATH = os.path.join(_PROJECT_ROOT, "assets", "fonts", "f1-bold.ttf")
VERSION_FONT_PATH = os.path.join(_PROJECT_ROOT, "assets", "fonts", "Roboto-Regular.ttf")

DEFAULT_OUT_PATH = os.path.join(_PROJECT_ROOT, "build", "splash", "splash.png")

# -------------------------------------- FUNCTIONS ---------------------------------------------------------------------

def _ensure_qt_app() -> QGuiApplication:
    """Return a QGuiApplication, creating one if this process does not have it yet.

    Returns:
        QGuiApplication: The application instance. Never None.
    """
    return QGuiApplication.instance() or QGuiApplication([])


def _load_font_family(ttf_path: str, fallback: str) -> str:
    """Register a bundled TTF with Qt and return the family name to paint with.

    Args:
        ttf_path (str): Absolute path to the .ttf file.
        fallback (str): Family name to use if the file is missing or unreadable.

    Returns:
        str: The resolved font family name.
    """
    if not os.path.isfile(ttf_path):
        print(f"gen_splash: font not found, falling back to {fallback}: {ttf_path}")
        return fallback

    font_id = QFontDatabase.addApplicationFont(ttf_path)
    if font_id < 0:
        print(f"gen_splash: Qt rejected font, falling back to {fallback}: {ttf_path}")
        return fallback

    families = QFontDatabase.applicationFontFamilies(font_id)
    return families[0] if families else fallback


def _font_at_points(family: str, point_size: int) -> QFont:
    """Build a font sized in points (scales with the display's logical DPI).

    Args:
        family (str): Font family name.
        point_size (int): Size in points.

    Returns:
        QFont: The requested font.
    """
    return QFont(family, point_size)


def _font_at_pixels(family: str, pixel_size: int) -> QFont:
    """Build a font sized in exact pixels, independent of DPI.

    Args:
        family (str): Font family name.
        pixel_size (int): Size in pixels.

    Returns:
        QFont: The requested font.
    """
    font = QFont(family)
    font.setPixelSize(pixel_size)
    return font


def _text_width(font: QFont, text: str) -> int:
    """Measure how wide `text` will be when drawn in `font`.

    Args:
        font (QFont): Font the text will be drawn in.
        text (str): The text to measure.

    Returns:
        int: Width in pixels.
    """
    return QFontMetrics(font).horizontalAdvance(text)


def _truncate_with_ellipsis(font: QFont, text: str, available_w: int) -> str:
    """Shorten `text` with a trailing ellipsis so it fits within `available_w`.

    Args:
        font (QFont): Font the text will be drawn in.
        text (str): The text to shorten.
        available_w (int): Width budget in pixels.

    Returns:
        str: The text, elided on the right if it did not fit.
    """
    return QFontMetrics(font).elidedText(text, Qt.ElideRight, available_w)


def _fit_text(text: str, family: str, available_w: int, max_pt: int, min_pt: int) -> tuple[QFont, str]:
    """Shrink (then elide) text until it fits the available width.

    Neither string painted here has a fixed length. The version is 'X.Y.Z' on release builds but
    the git-derived 'dev_<branch>_<sha>_<clean|dirty>' locally, which can exceed 40 characters on
    a long branch name; the title would clip too if APP_NAME were ever renamed to something
    longer. Stepping the point size down keeps both readable instead of running off the canvas.

    Args:
        text (str): The text to draw.
        family (str): Font family to use.
        available_w (int): Width budget in pixels.
        max_pt (int): Preferred (largest) point size.
        min_pt (int): Smallest point size to shrink to before eliding.

    Returns:
        tuple[QFont, str]: The font to paint with, and the (possibly elided) text.
    """
    for point_size in range(max_pt, min_pt - 1, -1):
        font = _font_at_points(family, point_size)
        if _text_width(font, text) <= available_w:
            return font, text

    # Still too wide at the smallest size: elide rather than overflow the canvas.
    font = _font_at_points(family, min_pt)
    return font, _truncate_with_ellipsis(font, text, available_w)


def _new_canvas() -> QImage:
    """Create the splash-sized image, pre-filled with the background colour.

    Returns:
        QImage: A blank canvas ready to be painted on.
    """
    image = QImage(CANVAS_W, CANVAS_H, QImage.Format_RGB32)
    image.fill(QColor(BG_COLOR))
    return image


def _enable_smooth_rendering(painter: QPainter) -> None:
    """Turn on antialiasing for shapes, text and scaled images.

    Args:
        painter (QPainter): The painter to configure.
    """
    painter.setRenderHints(
        QPainter.Antialiasing | QPainter.TextAntialiasing | QPainter.SmoothPixmapTransform
    )


def _load_scaled_logo(path: str, size: int) -> Optional[QPixmap]:
    """Load the app icon and scale it to a `size` x `size` box, preserving aspect ratio.

    Args:
        path (str): Path to the image file.
        size (int): Target box size in pixels.

    Returns:
        Optional[QPixmap]: The scaled icon, or None if the file is missing.
    """
    if not os.path.isfile(path):
        print(f"gen_splash: logo not found, splash will have no icon: {path}")
        return None

    return QPixmap(path).scaled(size, size, Qt.KeepAspectRatio, Qt.SmoothTransformation)


def _draw_image(painter: QPainter, x: int, y: int, pixmap: QPixmap) -> None:
    """Draw `pixmap` with its top-left corner at (x, y).

    Args:
        painter (QPainter): The painter to draw with.
        x (int): Left edge, in pixels from the canvas's left.
        y (int): Top edge, in pixels from the canvas's top.
        pixmap (QPixmap): The image to draw.
    """
    painter.drawPixmap(x, y, pixmap)


def _draw_text(painter: QPainter, x: int, y: int, text: str, font: QFont, color: str) -> None:
    """Draw `text` with its baseline starting at (x, y).

    Note that y is the text *baseline*, not its top edge - Qt's drawText and PyInstaller's
    text_pos agree on this, which is what keeps the two coordinate systems interchangeable.

    Args:
        painter (QPainter): The painter to draw with.
        x (int): Left edge of the text, in pixels from the canvas's left.
        y (int): Text baseline, in pixels from the canvas's top.
        text (str): The text to draw.
        font (QFont): Font to draw it in.
        color (str): Colour as an HTML code, e.g. '#b0b0b0'.
    """
    painter.setPen(QColor(color))
    painter.setFont(font)
    painter.drawText(x, y, text)


def _save_png(image: QImage, out_path: str) -> str:
    """Write `image` to disk as a PNG, creating parent directories as needed.

    Args:
        image (QImage): The image to save.
        out_path (str): Destination path.

    Returns:
        str: The absolute path written to.

    Raises:
        RuntimeError: If Qt fails to save the image.
    """
    out_path = os.path.abspath(out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    if not image.save(out_path, "PNG"):
        raise RuntimeError(f"Failed to write splash image to {out_path}")

    return out_path


def render_splash(out_path: str = DEFAULT_OUT_PATH) -> str:
    """Render the splash PNG and write it to disk.

    Args:
        out_path (str): Destination path for the PNG. Parent directories are created.

    Returns:
        str: The absolute path the image was written to.

    Raises:
        RuntimeError: If Qt fails to save the image.
    """
    _ensure_qt_app()

    title_family = _load_font_family(TITLE_FONT_PATH, "Arial")
    version_family = _load_font_family(VERSION_FONT_PATH, "Arial")
    version_str = get_version()

    image = _new_canvas()
    painter = QPainter(image)
    try:
        _enable_smooth_rendering(painter)

        # Left: app icon.
        logo = _load_scaled_logo(LOGO_PATH, LOGO_SIZE)
        if logo is not None:
            _draw_image(painter, LOGO_X, LOGO_Y, logo)

        available_w = CANVAS_W - TEXT_X - TEXT_RIGHT_MARGIN

        # Right: app name (major text), left-aligned to the text column.
        title_font, title_text = _fit_text(APP_NAME, title_family, available_w, TITLE_PT_MAX, TITLE_PT_MIN)
        _draw_text(painter, TEXT_X, TITLE_BASELINE_Y, title_text, title_font, TITLE_COLOR)

        # Under it: version (minor text), right-aligned to the text column as in the reference design.
        version_font, version_text = _fit_text(
            version_str, version_family, available_w, VERSION_PT_MAX, VERSION_PT_MIN
        )
        version_x = TEXT_X + available_w - _text_width(version_font, version_text)
        _draw_text(painter, version_x, VERSION_BASELINE_Y, version_text, version_font, VERSION_COLOR)

        # Bottom-left: the static "loading" line.
        loading_font = _font_at_pixels(version_family, LOADING_PX)
        _draw_text(painter, LOADING_POS[0], LOADING_POS[1], LOADING_TEXT, loading_font, LOADING_COLOR)
    finally:
        painter.end()

    out_path = _save_png(image, out_path)
    print(f"gen_splash: wrote {CANVAS_W}x{CANVAS_H} splash to {out_path} (version={version_str})")
    return out_path


def main() -> None:
    """CLI entry point for previewing the splash image."""
    parser = argparse.ArgumentParser(description="Render the Pits n' Giggles splash screen image")
    parser.add_argument(
        "-o", "--output",
        default=DEFAULT_OUT_PATH,
        help=f"Output PNG path (default: {DEFAULT_OUT_PATH})",
    )
    args = parser.parse_args()
    render_splash(args.output)


if __name__ == "__main__":
    main()
