name: Lint with Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.3"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run pylint
        run: |
          poetry run pylint --rcfile scripts/.pylintrc apps lib
