name: Manual Unit Tests

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    env:
      POETRY_VERSION: 2.1.2  # Pin for reproducibility

    defaults:
      run:
        shell: bash  # Force bash shell on all OSes, including Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
            python -m pip install --upgrade pip
            curl -sSL https://install.python-poetry.org | python -
            if [ "$RUNNER_OS" = "Windows" ]; then
            echo "$APPDATA\Python\Scripts" >> $GITHUB_PATH
            else
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            fi
        shell: bash

      - name: Install dependencies
        run: |
          poetry install --no-root
        shell: bash

      - name: Run unit tests
        run: poetry run python tests/unit_tests.py
