name: Manual Unit Tests

on:
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust as needed

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true  # Creates .venv in the project root

      - name: Install dependencies
        run: poetry install --no-interaction --no-root  # Or remove --no-root if you want the current package installed

      - name: Run unit tests
        run: poetry run python tests/unit_tests.py
